export enum AuthSagaAction {
  START_REFRESH_TOKEN_WATCHING = "AUTH_SAGA/START_REFRESH_TOKEN_WATCHING",
  STOP_REFRESH_TOKEN_WATCHING = "AUTH_SAGA/STOP_REFRESH_TOKEN_WATCHING",
  STORE_ACCESS_TOKEN = "AUTH_SAGA/STORE_ACCESS_TOKEN",
  CLEAR_ACCESS_TOKEN = "AUTH_SAGA/CLEAR_ACCESS_TOKEN",
  STORE_REFRESH_TOKEN = "AUTH_SAGA/STORE_REFRESH_TOKEN",
  CLEAR_REFRESH_TOKEN = "AUTH_SAGA/CLEAR_REFRESH_TOKEN",
  STORE_USER = "AUTH_SAGA/STORE_USER",
  CLEAR_USER = "AUTH_SAGA/CLEAR_USER",
}
