// Generated by https://quicktype.io

export interface VehicleSearchResult {
  dist: number;
  driver: VehicleSearchResultDriver;
  lat: number;
  lng: number;
  vehicle: Vehicle;
}

export interface VehicleSearchResultDriver {
  email: string;
  name: string;
  nickname: string;
  picture: string;
  user_id: string;
}

export interface Vehicle {
  class: string;
  driver: VehicleSearchResultDriver;
  name: string;
  plate: string;
  seats: number;
  type: string;
  vehicle_id: string;
}
